### ISSUE TITLE
Advice: use default export

### ISSUE THREAD

**Issue by soody-1992** [tjx666/webpack-open-browser#1]
As a simple webpack plugin, not a collection of plugins, I think using default export maybe a better practice XD.

**Comment by tjx666** [comment]
In fact, I once thought about this problem。Most users use js and commonjs to config webpack.   In 
 commonjs, default export should be used like:

```javascript
const { default: WebpackOpenBrowser } = require('webpack-open-browser');
```
It's a little strange...
But now, I hava a better idea, I plan to support both:

```javascript
export class WebpackOpenBrowser {
// ...
}
export default WebpackOpenBrowser;
```

**Comment by soody-1992** [comment]
Awesome idea! Thanks for your work.

**Comment by tjx666** [comment]
I had published a new version to support default export
