### ISSUE TITLE
open in incognito mode

### ISSUE THREAD

**Issue by AlonsoK28** [tjx666/webpack-open-browser#25]
this could be possible? 😊

**Comment by tjx666** [comment]
I will support to pass args to browser tonight. Then you can pass argument to it for example `-incognito`.

ref: https://superuser.com/questions/153245/how-can-i-open-google-chrome-via-command-line-with-a-url-in-incognito-mode

**Comment by tjx666** [comment]
If you want to open url on MacOS Chrome with incognito, you can try follwing code:

```typescript
import { exec } from 'child_process';

exec('open --new -a "Google Chrome" --args --incognito "https://github.com/"');
```

For MacOS Developer Version Firfox:

```typescript
import { exec } from 'child_process';

exec('open --new -a "Firefox Developer Edition" --args -private "https://en.wikipedia.org/wiki/Main_Page"');

```

There isn't a cross platform method to open incognito window now.

Ref issues: https://github.com/sindresorhus/open/issues?q=is%3Aissue+is%3Aopen+incognito
